### ISSUE TITLE
The action requires to be on stable

### ISSUE THREAD

**Issue by gaetschwartz** [dart-code-checker/dart-code-metrics-action#56] opened 2021-08-19 12:47 UTC
As of now there doesn't seem to be any way of setting the flutter channel used by the action, so it can fail when other channels are used.

Would be great to have a way to pass the desired flutter channel as an argument.

See here: https://github.com/gaetschwartz/swift_travel/runs/3371615025

![image](https://user-images.githubusercontent.com/25441359/130070896-42480c79-98f8-4318-a460-e9361674b5f9.png)

**Comment by dkrutskikh** [comment] 2021-09-12 14:28
@gaetschwartz apologies for the delayed response. Is it actual now?

**Comment by dkrutskikh** [comment] 2021-09-18 14:55
@gaetschwartz I will close this issue, feel free to reopen if the problem is still relevant

**Closed by dkrutskikh** 2021-09-18 14:55 UTC
Labels: type: bug
