### ISSUE TITLE
[Question] How do CI with a Monorepo?

### ISSUE THREAD

**Issue by ItaloF532** [dart-code-checker/dart-code-metrics-action#113] opened 2022-08-22 14:48 UTC
**What do you want to discuss?**

Hi, I work with a monorepo and a trying to implement the dart code metrics CI, but I don't found any example of it.
I achieved with melos in CI, but without dart code metrics CI, I can't have comments for te code issues in PR.

Can you guys give me an example of how can I use the dart code metrics with a mono repo in CI? Please

**Comment by incendial** [comment] 2022-08-28 11:03
Closing this as duplicate of https://github.com/dart-code-checker/dart-code-metrics/issues/970, let's continue there

**Closed by incendial** 2022-08-28 11:03 UTC
